export const AIRLINES = [
  'American Airlines',
  'Delta Air Lines',
  'United Airlines',
  'Southwest Airlines',
  'Ryanair',
  'China Southern Airlines',
  'China Eastern Airlines',
  'Lufthansa',
  'British Airways',
  'Air France',
  'Turkish Airlines',
  'Qatar Airways',
  'Emirates',
  'Ethiopian Airlines',
  'KLM Royal Dutch Airlines',
  'Air Canada',
  'Qantas Airways',
  'Cathay Pacific Airways',
  'Singapore Airlines',
  'All Nippon Airways',
  'Japan Airlines',
  'Iberia',
  'Virgin Atlantic',
  'Etihad Airways',
  'Malaysia Airlines',
  'IndiGo',
  'Thai Airways',
  'Scoot',
  'Fiji Airways',
  'Bangkok Airways',
  'AirAsia',
  'Saudia',
  'STARLUX Airlines',
  'Swiss International Air Lines',
  'EVA Air',
  'Austrian Airlines',
  'Air New Zealand',
  'Finnair',
  'Garuda Indonesia',
  'Vueling Airlines',
  'Asiana Airlines',
  'Volotea',
  'Porter Airlines',
  'Gulf Air',
  'Air Astana',
  'China Airlines',
  'Virgin Australia',
  'Aer Lingus',
  'Aeroflot',
  'Aeromexico',
  'Aegean Airlines',
  'Alaska Airlines',
  'Alitalia',
  'Aerolíneas Argentinas',
  'AeroRepublica',
  'Air Arabia',
  'Air Algérie',
  'Air Baltic',
  'Air India',
  'Air Malta',
  'Air Namibia',
  'Air Niugini',
  'Air Serbia',
  'Air Tahiti Nui',
  'Air Transat',
  'Allegiant Air',
  'Arkia Israeli Airlines',
  'Azur Air',
  'Binter Canarias',
  'Boliviana de Aviación',
  'Brussels Airlines',
  'Copa Airlines',
  'Corsair International',
  'Czech Airlines',
  'Dragonair',
  'EgyptAir',
  'El Al',
  'Ethiopian Mozambique Airlines',
  'Eurowings',
  'Fiji Airways',
  'Flydubai',
  'GOL Linhas Aéreas',
  'Hainan Airlines',
  'Hawaiian Airlines',
  'Icelandair',
  'Jetstar Airways',
  'Kenya Airways',
  'Korean Air',
  'LOT Polish Airlines',
  'Luxair',
  'Mango Airlines',
  'Mexicana de Aviación',
  'Norse Atlantic Airways',
  'Norwegian Air Shuttle',
  'Oman Air',
  'Pakistan International Airlines',
  'Pegasus Airlines',
  'Philippine Airlines',
  'Precision Air',
  'QantasLink',
  'Royal Air Maroc',
  'Royal Jordanian',
  'S7 Airlines',
  'SAS Scandinavian Airlines',
  'Shenzhen Airlines',
  'Singapore Airlines Cargo',
  'Spirit Airlines',

  'SriLankan Airlines',
  'Sun Country Airlines',
  'TAP Air Portugal',
  'TAROM',
  'Transavia',
  'Tunisair',
  'Turkmenistan Airlines',
  'Türk Hava Kurumu',
  'Uganda Airlines',
  'Ultra Air',
  'Uzbekistan Airways',
  'Vietnam Airlines',
  'Volaris',
  'WestJet',
  'Wizz Air',
  'XiamenAir',
  'Yemenia',
  'Zambia Airways',
  'Air Mauritius',
  'Air Zimbabwe',
  'Somon Air',
  'Air Burkina',
  'Air Côte d’Ivoire',
  'TAAG Angola Airlines',
  'LAM Mozambique Airlines',
  'South African Airways',
  'Airlink',
  'Air Senegal',
  'ASKY Airlines',
  'RwandAir',
  'Fastjet',
  'Jambojet',
  'FlySafair',
  'Safair',
  'Kulula',
  'Comair',
  'Precision Air',
  'Auric Air',
  'Air Tanzania',
  'Fly540',
  'Air Botswana',
  'Edelweiss Air',
  'Helvetic Airways',
  'Neos',
  'TUI fly Belgium',
  'TUI fly Netherlands',
  'TUI fly Deutschland',
  'TUI Airways',
  'Jet2',
  'SunExpress',
  'Condor',
  'Level',
  'Air Europa',
  'Blue Panorama',
  'Meridiana',
  'Air Dolomiti',
  'Volotea',
  'Viva Aerobus',
  'Lynx Air',
  'Flair Airlines',
  'Canadian North',
  'Air Inuit',
  'Air Creebec',
  'PAL Airlines (Canada)',
  'Avianca',
  'LATAM Colombia',
  'LATAM Peru',
  'LATAM Chile',
  'SKY Airline',
  'JetSmart',
  'EasyFly',
  'Satena',
  'Conviasa',
  'Surinam Airways',
  'Caribbean Airlines',
  'Cayman Airways',
  'Bahamasair',
  'LIAT',
  'Winair',
  'Silver Airways',
  'Cape Air',
  'Boutique Air',
  'Surfair',
  'Rex Regional Express',
  'Alliance Airlines',
  'Airnorth',
  'Solomon Airlines',
  'Air Vanuatu',
  'Air Kiribati',
  'Nauru Airlines',
  'Aircalin',
  'Air Tahiti',
  'Jetstar Asia',
  'HK Express',
  'HK Airlines',
  'VietJet Air',
  'Bamboo Airways',
  'Bangladesh Biman',
  'US-Bangla Airlines',
  'Druk Air',
  'Bhutan Airlines',
  'Royal Brunei Airlines',
  'China United Airlines',
  'Loong Air',
  '9 Air',
  'Shandong Airlines',
  'Sichuan Airlines',
  'Spring Airlines',
  'Tibet Airlines',
  'Urumqi Air',

  'Okay Airways',
  'Hebei Airlines',
  'Jiangxi Air',
  'Joy Air',
  'Great Wall Airlines',
  'YTO Cargo Airlines',
  'SF Airlines',
  'China Postal Airlines',
  'Air Do',
  'Peach Aviation',
  'Vanilla Air',
  'Skymark Airlines',
  'Star Flyer',
  'T’way Air',
  'Jeju Air',
  'Jin Air',
  'Air Busan',
  'Air Seoul',
  'Eastar Jet',
  'Garuda Indonesia Explore',
  'Citilink',
  'Lion Air',
  'Batik Air',
  'Wings Air',
  'Super Air Jet',
  'Sriwijaya Air',
  'NAM Air',
  'TransNusa',
  'Myanmar Airways International',
  'Air KBZ',
  'Nok Air',
  'Thai Lion Air',
  'Thai Smile',
  'Go First',
  'SpiceJet',
  'Vistara',
  'Air India Express',
  'Alliance Air',
  'Akasa Air',
  'Iraqi Airways',
  'Mahan Air',
  'Qatar Amiri Flight',
  'Oman Air Cargo',
  'Jazeera Airways',
  'Kuwait Airways',
  'Flynas',
  'Flyadeal',
  'Middle East Airlines',
  'Royal Falcon',
  'Syrian Air',
  'Azerbaijan Airlines',
  'Georgian Airways',
  'Uzbekistan Express',
  'SCAT Airlines',
  'Air Astana FlyArystan',
  'Belavia',
  'Motor Sich Airlines',
  'Ukraine International Airlines',
  'Air Moldova',
  'Moldavian Airlines',
  'Tarom Regional',
  'Air Baltic Charter',
  'Nordwind Airlines',
  'Pobeda',
  'Red Wings',
  'UTair',
  'Yakutia Airlines',
  'Aurora',
  'S7 Siberia Regional',
  'Air Koryo',
  'Kam Air',
  'Ariana Afghan Airlines',
  'Iran Air',
  'Iran Aseman Airlines',
  'Meraj Air',
  'Qeshm Air',
  'Caspian Airlines',
  'Taban Air',
  'Astra Airlines',
  'Olympic Air',
  'Sky Express Greece',
  'Blue Air',
  'Wizz Air UK',
  'Wizz Air Abu Dhabi',
  'Smartwings',
  'CSA Czech Airlines',
  'LOT Charters',
  'Brussels Airlines Regional',
  'Air Antwerp',
  'Luxair Regional',
  'Icelandair Connect',
  'Play Airlines',
  'Aurigny Air Services',
  'Blue Islands',
  'Loganair',
  'Eastern Airways',
  'Bamboo Airways Cargo',
  'Nepal Airlines',
  'Himalaya Airlines',
  'Yeti Airlines',
  'Buddha Air',
  'Pakistan International Cargo',
  'SereneAir',
  'AirSial',
  'Kamchatka Air',
  'Corendon Airlines',
  'Pegasus Asia',
  'Air Serbia Aviolet',
  'Montenegro Airlines',
  'Croatia Airlines',
  'BosniaFly',
  'Air Montenegro',
  'TAR Aerolíneas',
  'Interjet',
  'Aeromar',
  'Magnicharters',
  'Amaszonas',
  'EcoJet',
  'Boliviana Regional',
  'Avianca Ecuador',
  'Avianca Costa Rica',
  'Star Perú',
  'Peruvian Airlines',
];
