export const COUNTRIES = [
  {
    name: 'Afghanistan',
    iso2: 'AF',
    iso3: 'AFG',
    flag: 'https://flagcdn.com/af.svg',
    currency: 'AFN',
    capital: 'Kabul',
    region: 'Asia',
    coordinates: { lat: 34.5289, lng: 69.1725 },
  },
  {
    name: 'Albania',
    iso2: 'AL',
    iso3: 'ALB',
    flag: 'https://flagcdn.com/al.svg',
    currency: 'ALL',
    capital: 'Tirana',
    region: 'Europe',
    coordinates: { lat: 41.3275, lng: 19.8189 },
  },
  {
    name: 'Algeria',
    iso2: 'DZ',
    iso3: 'DZA',
    flag: 'https://flagcdn.com/dz.svg',
    currency: 'DZD',
    capital: 'Algiers',
    region: 'Africa',
    coordinates: { lat: 36.7525, lng: 3.04197 },
  },
  {
    name: 'Andorra',
    iso2: 'AD',
    iso3: 'AND',
    flag: 'https://flagcdn.com/ad.svg',
    currency: 'EUR',
    capital: 'Andorra la Vella',
    region: 'Europe',
    coordinates: { lat: 42.5078, lng: 1.5211 },
  },
  {
    name: 'Angola',
    iso2: 'AO',
    iso3: 'AGO',
    flag: 'https://flagcdn.com/ao.svg',
    currency: 'AOA',
    capital: 'Luanda',
    region: 'Africa',
    coordinates: { lat: -8.8368, lng: 13.2343 },
  },
  {
    name: 'Antigua and Barbuda',
    iso2: 'AG',
    iso3: 'ATG',
    flag: 'https://flagcdn.com/ag.svg',
    currency: 'XCD',
    capital: "Saint John's",
    region: 'North America',
    coordinates: { lat: 17.1274, lng: -61.8468 },
  },
  {
    name: 'Argentina',
    iso2: 'AR',
    iso3: 'ARG',
    flag: 'https://flagcdn.com/ar.svg',
    currency: 'ARS',
    capital: 'Buenos Aires',
    region: 'South America',
    coordinates: { lat: -34.6037, lng: -58.3816 },
  },
  {
    name: 'Armenia',
    iso2: 'AM',
    iso3: 'ARM',
    flag: 'https://flagcdn.com/am.svg',
    currency: 'AMD',
    capital: 'Yerevan',
    region: 'Asia',
    coordinates: { lat: 40.1772, lng: 44.5035 },
  },
  {
    name: 'Australia',
    iso2: 'AU',
    iso3: 'AUS',
    flag: 'https://flagcdn.com/au.svg',
    currency: 'AUD',
    capital: 'Canberra',
    region: 'Oceania',
    coordinates: { lat: -35.2809, lng: 149.13 },
  },
  {
    name: 'Austria',
    iso2: 'AT',
    iso3: 'AUT',
    flag: 'https://flagcdn.com/at.svg',
    currency: 'EUR',
    capital: 'Vienna',
    region: 'Europe',
    coordinates: { lat: 48.2082, lng: 16.3738 },
  },
  {
    name: 'Azerbaijan',
    iso2: 'AZ',
    iso3: 'AZE',
    flag: 'https://flagcdn.com/az.svg',
    currency: 'AZN',
    capital: 'Baku',
    region: 'Asia',
    coordinates: { lat: 40.4093, lng: 49.8671 },
  },
  {
    name: 'Bahamas',
    iso2: 'BS',
    iso3: 'BHS',
    flag: 'https://flagcdn.com/bs.svg',
    currency: 'BSD',
    capital: 'Nassau',
    region: 'North America',
    coordinates: { lat: 25.047, lng: -77.3554 },
  },
  {
    name: 'Bahrain',
    iso2: 'BH',
    iso3: 'BHR',
    flag: 'https://flagcdn.com/bh.svg',
    currency: 'BHD',
    capital: 'Manama',
    region: 'Asia',
    coordinates: { lat: 26.2285, lng: 50.5861 },
  },
  {
    name: 'Bangladesh',
    iso2: 'BD',
    iso3: 'BGD',
    flag: 'https://flagcdn.com/bd.svg',
    currency: 'BDT',
    capital: 'Dhaka',
    region: 'Asia',
    coordinates: { lat: 23.8103, lng: 90.4125 },
  },
  {
    name: 'Barbados',
    iso2: 'BB',
    iso3: 'BRB',
    flag: 'https://flagcdn.com/bb.svg',
    currency: 'BBD',
    capital: 'Bridgetown',
    region: 'North America',
    coordinates: { lat: 13.0975, lng: -59.6165 },
  },
  {
    name: 'Belarus',
    iso2: 'BY',
    iso3: 'BLR',
    flag: 'https://flagcdn.com/by.svg',
    currency: 'BYN',
    capital: 'Minsk',
    region: 'Europe',
    coordinates: { lat: 53.9045, lng: 27.5615 },
  },
  {
    name: 'Belgium',
    iso2: 'BE',
    iso3: 'BEL',
    flag: 'https://flagcdn.com/be.svg',
    currency: 'EUR',
    capital: 'Brussels',
    region: 'Europe',
    coordinates: { lat: 50.8503, lng: 4.3517 },
  },
  {
    name: 'Belize',
    iso2: 'BZ',
    iso3: 'BLZ',
    flag: 'https://flagcdn.com/bz.svg',
    currency: 'BZD',
    capital: 'Belmopan',
    region: 'North America',
    coordinates: { lat: 17.2514, lng: -88.7669 },
  },
  {
    name: 'Benin',
    iso2: 'BJ',
    iso3: 'BEN',
    flag: 'https://flagcdn.com/bj.svg',
    currency: 'XOF',
    capital: 'Porto-Novo',
    region: 'Africa',
    coordinates: { lat: 6.4969, lng: 2.6289 },
  },
  {
    name: 'Bhutan',
    iso2: 'BT',
    iso3: 'BTN',
    flag: 'https://flagcdn.com/bt.svg',
    currency: 'BTN',
    capital: 'Thimphu',
    region: 'Asia',
    coordinates: { lat: 27.4712, lng: 89.6339 },
  },
  {
    name: 'Bolivia',
    iso2: 'BO',
    iso3: 'BOL',
    flag: 'https://flagcdn.com/bo.svg',
    currency: 'BOB',
    capital: 'Sucre',
    region: 'South America',
    coordinates: { lat: -19.0196, lng: -65.2619 },
  },
  {
    name: 'Bosnia and Herzegovina',
    iso2: 'BA',
    iso3: 'BIH',
    flag: 'https://flagcdn.com/ba.svg',
    currency: 'BAM',
    capital: 'Sarajevo',
    region: 'Europe',
    coordinates: { lat: 43.8563, lng: 18.4131 },
  },
  {
    name: 'Botswana',
    iso2: 'BW',
    iso3: 'BWA',
    flag: 'https://flagcdn.com/bw.svg',
    currency: 'BWP',
    capital: 'Gaborone',
    region: 'Africa',
    coordinates: { lat: -24.6282, lng: 25.9231 },
  },
  {
    name: 'Brazil',
    iso2: 'BR',
    iso3: 'BRA',
    flag: 'https://flagcdn.com/br.svg',
    currency: 'BRL',
    capital: 'Brasília',
    region: 'South America',
    coordinates: { lat: -15.7939, lng: -47.8828 },
  },
  {
    name: 'Brunei',
    iso2: 'BN',
    iso3: 'BRN',
    flag: 'https://flagcdn.com/bn.svg',
    currency: 'BND',
    capital: 'Bandar Seri Begawan',
    region: 'Asia',
    coordinates: { lat: 4.9031, lng: 114.9398 },
  },
  {
    name: 'Bulgaria',
    iso2: 'BG',
    iso3: 'BGR',
    flag: 'https://flagcdn.com/bg.svg',
    currency: 'BGN',
    capital: 'Sofia',
    region: 'Europe',
    coordinates: { lat: 42.6977, lng: 23.3219 },
  },
  {
    name: 'Burkina Faso',
    iso2: 'BF',
    iso3: 'BFA',
    flag: 'https://flagcdn.com/bf.svg',
    currency: 'XOF',
    capital: 'Ouagadougou',
    region: 'Africa',
    coordinates: { lat: 12.3714, lng: -1.5197 },
  },
  {
    name: 'Burundi',
    iso2: 'BI',
    iso3: 'BDI',
    flag: 'https://flagcdn.com/bi.svg',
    currency: 'BIF',
    capital: 'Gitega',
    region: 'Africa',
    coordinates: { lat: -3.4264, lng: 29.9306 },
  },
  {
    name: 'Cabo Verde',
    iso2: 'CV',
    iso3: 'CPV',
    flag: 'https://flagcdn.com/cv.svg',
    currency: 'CVE',
    capital: 'Praia',
    region: 'Africa',
    coordinates: { lat: 14.933, lng: -23.5133 },
  },
  {
    name: 'Cambodia',
    iso2: 'KH',
    iso3: 'KHM',
    flag: 'https://flagcdn.com/kh.svg',
    currency: 'KHR',
    capital: 'Phnom Penh',
    region: 'Asia',
    coordinates: { lat: 11.5564, lng: 104.9282 },
  },
  {
    name: 'Cameroon',
    iso2: 'CM',
    iso3: 'CMR',
    flag: 'https://flagcdn.com/cm.svg',
    currency: 'XAF',
    capital: 'Yaoundé',
    region: 'Africa',
    coordinates: { lat: 3.848, lng: 11.5021 },
  },
  {
    name: 'Canada',
    iso2: 'CA',
    iso3: 'CAN',
    flag: 'https://flagcdn.com/ca.svg',
    currency: 'CAD',
    capital: 'Ottawa',
    region: 'North America',
    coordinates: { lat: 45.4215, lng: -75.6972 },
  },
  {
    name: 'Central African Republic',
    iso2: 'CF',
    iso3: 'CAF',
    flag: 'https://flagcdn.com/cf.svg',
    currency: 'XAF',
    capital: 'Bangui',
    region: 'Africa',
    coordinates: { lat: 4.3947, lng: 18.5582 },
  },
  {
    name: 'Chad',
    iso2: 'TD',
    iso3: 'TCD',
    flag: 'https://flagcdn.com/td.svg',
    currency: 'XAF',
    capital: "N'Djamena",
    region: 'Africa',
    coordinates: { lat: 12.1348, lng: 15.0557 },
  },
  {
    name: 'Chile',
    iso2: 'CL',
    iso3: 'CHL',
    flag: 'https://flagcdn.com/cl.svg',
    currency: 'CLP',
    capital: 'Santiago',
    region: 'South America',
    coordinates: { lat: -33.4489, lng: -70.6693 },
  },
  {
    name: 'China',
    iso2: 'CN',
    iso3: 'CHN',
    flag: 'https://flagcdn.com/cn.svg',
    currency: 'CNY',
    capital: 'Beijing',
    region: 'Asia',
    coordinates: { lat: 39.9042, lng: 116.4074 },
  },
  {
    name: 'Colombia',
    iso2: 'CO',
    iso3: 'COL',
    flag: 'https://flagcdn.com/co.svg',
    currency: 'COP',
    capital: 'Bogotá',
    region: 'South America',
    coordinates: { lat: 4.711, lng: -74.0721 },
  },
  {
    name: 'Comoros',
    iso2: 'KM',
    iso3: 'COM',
    flag: 'https://flagcdn.com/km.svg',
    currency: 'KMF',
    capital: 'Moroni',
    region: 'Africa',
    coordinates: { lat: -11.7172, lng: 43.2473 },
  },
  {
    name: 'Congo, Democratic Republic',
    iso2: 'CD',
    iso3: 'COD',
    flag: 'https://flagcdn.com/cd.svg',
    currency: 'CDF',
    capital: 'Kinshasa',
    region: 'Africa',
    coordinates: { lat: -4.4419, lng: 15.2663 },
  },
  {
    name: 'Congo, Republic',
    iso2: 'CG',
    iso3: 'COG',
    flag: 'https://flagcdn.com/cg.svg',
    currency: 'XAF',
    capital: 'Brazzaville',
    region: 'Africa',
    coordinates: { lat: -4.2634, lng: 15.2429 },
  },
  {
    name: 'Costa Rica',
    iso2: 'CR',
    iso3: 'CRI',
    flag: 'https://flagcdn.com/cr.svg',
    currency: 'CRC',
    capital: 'San José',
    region: 'North America',
    coordinates: { lat: 9.9281, lng: -84.0907 },
  },
  {
    name: 'Croatia',
    iso2: 'HR',
    iso3: 'HRV',
    flag: 'https://flagcdn.com/hr.svg',
    currency: 'EUR',
    capital: 'Zagreb',
    region: 'Europe',
    coordinates: { lat: 45.815, lng: 15.9819 },
  },
  {
    name: 'Cuba',
    iso2: 'CU',
    iso3: 'CUB',
    flag: 'https://flagcdn.com/cu.svg',
    currency: 'CUP',
    capital: 'Havana',
    region: 'North America',
    coordinates: { lat: 23.1136, lng: -82.3666 },
  },
  {
    name: 'Cyprus',
    iso2: 'CY',
    iso3: 'CYP',
    flag: 'https://flagcdn.com/cy.svg',
    currency: 'EUR',
    capital: 'Nicosia',
    region: 'Europe',
    coordinates: { lat: 35.1856, lng: 33.3823 },
  },
  {
    name: 'Czech Republic',
    iso2: 'CZ',
    iso3: 'CZE',
    flag: 'https://flagcdn.com/cz.svg',
    currency: 'CZK',
    capital: 'Prague',
    region: 'Europe',
    coordinates: { lat: 50.0755, lng: 14.4378 },
  },
  {
    name: 'Denmark',
    iso2: 'DK',
    iso3: 'DNK',
    flag: 'https://flagcdn.com/dk.svg',
    currency: 'DKK',
    capital: 'Copenhagen',
    region: 'Europe',
    coordinates: { lat: 55.6761, lng: 12.5683 },
  },
  {
    name: 'Djibouti',
    iso2: 'DJ',
    iso3: 'DJI',
    flag: 'https://flagcdn.com/dj.svg',
    currency: 'DJF',
    capital: 'Djibouti',
    region: 'Africa',
    coordinates: { lat: 11.8251, lng: 42.5903 },
  },
  {
    name: 'Dominica',
    iso2: 'DM',
    iso3: 'DMA',
    flag: 'https://flagcdn.com/dm.svg',
    currency: 'XCD',
    capital: 'Roseau',
    region: 'North America',
    coordinates: { lat: 15.3092, lng: -61.3794 },
  },
  {
    name: 'Dominican Republic',
    iso2: 'DO',
    iso3: 'DOM',
    flag: 'https://flagcdn.com/do.svg',
    currency: 'DOP',
    capital: 'Santo Domingo',
    region: 'North America',
    coordinates: { lat: 18.4861, lng: -69.9312 },
  },
  {
    name: 'Ecuador',
    iso2: 'EC',
    iso3: 'ECU',
    flag: 'https://flagcdn.com/ec.svg',
    currency: 'USD',
    capital: 'Quito',
    region: 'South America',
    coordinates: { lat: -0.1807, lng: -78.4678 },
  },
  {
    name: 'Egypt',
    iso2: 'EG',
    iso3: 'EGY',
    flag: 'https://flagcdn.com/eg.svg',
    currency: 'EGP',
    capital: 'Cairo',
    region: 'Africa',
    coordinates: { lat: 30.0444, lng: 31.2357 },
  },
  {
    name: 'El Salvador',
    iso2: 'SV',
    iso3: 'SLV',
    flag: 'https://flagcdn.com/sv.svg',
    currency: 'USD',
    capital: 'San Salvador',
    region: 'North America',
    coordinates: { lat: 13.6929, lng: -89.2182 },
  },
  {
    name: 'Equatorial Guinea',
    iso2: 'GQ',
    iso3: 'GNQ',
    flag: 'https://flagcdn.com/gq.svg',
    currency: 'XAF',
    capital: 'Malabo',
    region: 'Africa',
    coordinates: { lat: 3.7504, lng: 8.7371 },
  },
  {
    name: 'Eritrea',
    iso2: 'ER',
    iso3: 'ERI',
    flag: 'https://flagcdn.com/er.svg',
    currency: 'ERN',
    capital: 'Asmara',
    region: 'Africa',
    coordinates: { lat: 15.3229, lng: 38.9251 },
  },
  {
    name: 'Estonia',
    iso2: 'EE',
    iso3: 'EST',
    flag: 'https://flagcdn.com/ee.svg',
    currency: 'EUR',
    capital: 'Tallinn',
    region: 'Europe',
    coordinates: { lat: 59.437, lng: 24.7536 },
  },
  {
    name: 'Eswatini',
    iso2: 'SZ',
    iso3: 'SWZ',
    flag: 'https://flagcdn.com/sz.svg',
    currency: 'SZL',
    capital: 'Mbabane',
    region: 'Africa',
    coordinates: { lat: -26.3054, lng: 31.1367 },
  },
  {
    name: 'Ethiopia',
    iso2: 'ET',
    iso3: 'ETH',
    flag: 'https://flagcdn.com/et.svg',
    currency: 'ETB',
    capital: 'Addis Ababa',
    region: 'Africa',
    coordinates: { lat: 9.0084, lng: 38.7578 },
  },
  {
    name: 'Fiji',
    iso2: 'FJ',
    iso3: 'FJI',
    flag: 'https://flagcdn.com/fj.svg',
    currency: 'FJD',
    capital: 'Suva',
    region: 'Oceania',
    coordinates: { lat: -18.1248, lng: 178.4501 },
  },
  {
    name: 'Finland',
    iso2: 'FI',
    iso3: 'FIN',
    flag: 'https://flagcdn.com/fi.svg',
    currency: 'EUR',
    capital: 'Helsinki',
    region: 'Europe',
    coordinates: { lat: 60.1699, lng: 24.9384 },
  },
  {
    name: 'France',
    iso2: 'FR',
    iso3: 'FRA',
    flag: 'https://flagcdn.com/fr.svg',
    currency: 'EUR',
    capital: 'Paris',
    region: 'Europe',
    coordinates: { lat: 48.8566, lng: 2.3522 },
  },
  {
    name: 'Gabon',
    iso2: 'GA',
    iso3: 'GAB',
    flag: 'https://flagcdn.com/ga.svg',
    currency: 'XAF',
    capital: 'Libreville',
    region: 'Africa',
    coordinates: { lat: 0.4162, lng: 9.4673 },
  },
  {
    name: 'Gambia',
    iso2: 'GM',
    iso3: 'GMB',
    flag: 'https://flagcdn.com/gm.svg',
    currency: 'GMD',
    capital: 'Banjul',
    region: 'Africa',
    coordinates: { lat: 13.4549, lng: -16.579 },
  },
  {
    name: 'Georgia',
    iso2: 'GE',
    iso3: 'GEO',
    flag: 'https://flagcdn.com/ge.svg',
    currency: 'GEL',
    capital: 'Tbilisi',
    region: 'Asia',
    coordinates: { lat: 41.7151, lng: 44.8271 },
  },
  {
    name: 'Germany',
    iso2: 'DE',
    iso3: 'DEU',
    flag: 'https://flagcdn.com/de.svg',
    currency: 'EUR',
    capital: 'Berlin',
    region: 'Europe',
    coordinates: { lat: 52.52, lng: 13.405 },
  },
  {
    name: 'Ghana',
    iso2: 'GH',
    iso3: 'GHA',
    flag: 'https://flagcdn.com/gh.svg',
    currency: 'GHS',
    capital: 'Accra',
    region: 'Africa',
    coordinates: { lat: 5.6037, lng: -0.187 },
  },
  {
    name: 'Greece',
    iso2: 'GR',
    iso3: 'GRC',
    flag: 'https://flagcdn.com/gr.svg',
    currency: 'EUR',
    capital: 'Athens',
    region: 'Europe',
    coordinates: { lat: 37.9838, lng: 23.7275 },
  },
  {
    name: 'Grenada',
    iso2: 'GD',
    iso3: 'GRD',
    flag: 'https://flagcdn.com/gd.svg',
    currency: 'XCD',
    capital: "St. George's",
    region: 'North America',
    coordinates: { lat: 12.0561, lng: -61.7488 },
  },
  {
    name: 'Guatemala',
    iso2: 'GT',
    iso3: 'GTM',
    flag: 'https://flagcdn.com/gt.svg',
    currency: 'GTQ',
    capital: 'Guatemala City',
    region: 'North America',
    coordinates: { lat: 14.6349, lng: -90.5069 },
  },
  {
    name: 'Guinea',
    iso2: 'GN',
    iso3: 'GIN',
    flag: 'https://flagcdn.com/gn.svg',
    currency: 'GNF',
    capital: 'Conakry',
    region: 'Africa',
    coordinates: { lat: 9.6412, lng: -13.5784 },
  },
  {
    name: 'Guinea-Bissau',
    iso2: 'GW',
    iso3: 'GNB',
    flag: 'https://flagcdn.com/gw.svg',
    currency: 'XOF',
    capital: 'Bissau',
    region: 'Africa',
    coordinates: { lat: 11.8636, lng: -15.5977 },
  },
  {
    name: 'Guyana',
    iso2: 'GY',
    iso3: 'GUY',
    flag: 'https://flagcdn.com/gy.svg',
    currency: 'GYD',
    capital: 'Georgetown',
    region: 'South America',
    coordinates: { lat: 6.8013, lng: -58.1551 },
  },
  {
    name: 'Haiti',
    iso2: 'HT',
    iso3: 'HTI',
    flag: 'https://flagcdn.com/ht.svg',
    currency: 'HTG',
    capital: 'Port-au-Prince',
    region: 'North America',
    coordinates: { lat: 18.5944, lng: -72.3074 },
  },
  {
    name: 'Honduras',
    iso2: 'HN',
    iso3: 'HND',
    flag: 'https://flagcdn.com/hn.svg',
    currency: 'HNL',
    capital: 'Tegucigalpa',
    region: 'North America',
    coordinates: { lat: 14.0723, lng: -87.1921 },
  },
  {
    name: 'Hungary',
    iso2: 'HU',
    iso3: 'HUN',
    flag: 'https://flagcdn.com/hu.svg',
    currency: 'HUF',
    capital: 'Budapest',
    region: 'Europe',
    coordinates: { lat: 47.4979, lng: 19.0402 },
  },
  {
    name: 'Iceland',
    iso2: 'IS',
    iso3: 'ISL',
    flag: 'https://flagcdn.com/is.svg',
    currency: 'ISK',
    capital: 'Reykjavik',
    region: 'Europe',
    coordinates: { lat: 64.1466, lng: -21.9426 },
  },
  {
    name: 'India',
    iso2: 'IN',
    iso3: 'IND',
    flag: 'https://flagcdn.com/in.svg',
    currency: 'INR',
    capital: 'New Delhi',
    region: 'Asia',
    coordinates: { lat: 28.6139, lng: 77.209 },
  },
  {
    name: 'Indonesia',
    iso2: 'ID',
    iso3: 'IDN',
    flag: 'https://flagcdn.com/id.svg',
    currency: 'IDR',
    capital: 'Jakarta',
    region: 'Asia',
    coordinates: { lat: -6.2088, lng: 106.8456 },
  },
  {
    name: 'Iran',
    iso2: 'IR',
    iso3: 'IRN',
    flag: 'https://flagcdn.com/ir.svg',
    currency: 'IRR',
    capital: 'Tehran',
    region: 'Asia',
    coordinates: { lat: 35.6892, lng: 51.389 },
  },
  {
    name: 'Iraq',
    iso2: 'IQ',
    iso3: 'IRQ',
    flag: 'https://flagcdn.com/iq.svg',
    currency: 'IQD',
    capital: 'Baghdad',
    region: 'Asia',
    coordinates: { lat: 33.3152, lng: 44.3661 },
  },
  {
    name: 'Ireland',
    iso2: 'IE',
    iso3: 'IRL',
    flag: 'https://flagcdn.com/ie.svg',
    currency: 'EUR',
    capital: 'Dublin',
    region: 'Europe',
    coordinates: { lat: 53.3498, lng: -6.2603 },
  },
  {
    name: 'Israel',
    iso2: 'IL',
    iso3: 'ISR',
    flag: 'https://flagcdn.com/il.svg',
    currency: 'ILS',
    capital: 'Jerusalem',
    region: 'Asia',
    coordinates: { lat: 31.7683, lng: 35.2137 },
  },
  {
    name: 'Italy',
    iso2: 'IT',
    iso3: 'ITA',
    flag: 'https://flagcdn.com/it.svg',
    currency: 'EUR',
    capital: 'Rome',
    region: 'Europe',
    coordinates: { lat: 41.9028, lng: 12.4964 },
  },
  {
    name: 'Jamaica',
    iso2: 'JM',
    iso3: 'JAM',
    flag: 'https://flagcdn.com/jm.svg',
    currency: 'JMD',
    capital: 'Kingston',
    region: 'North America',
    coordinates: { lat: 17.9714, lng: -76.792 },
  },
  {
    name: 'Japan',
    iso2: 'JP',
    iso3: 'JPN',
    flag: 'https://flagcdn.com/jp.svg',
    currency: 'JPY',
    capital: 'Tokyo',
    region: 'Asia',
    coordinates: { lat: 35.6762, lng: 139.6503 },
  },
  {
    name: 'Jordan',
    iso2: 'JO',
    iso3: 'JOR',
    flag: 'https://flagcdn.com/jo.svg',
    currency: 'JOD',
    capital: 'Amman',
    region: 'Asia',
    coordinates: { lat: 31.9454, lng: 35.9284 },
  },
  {
    name: 'Kazakhstan',
    iso2: 'KZ',
    iso3: 'KAZ',
    flag: 'https://flagcdn.com/kz.svg',
    currency: 'KZT',
    capital: 'Astana',
    region: 'Asia',
    coordinates: { lat: 51.1605, lng: 71.4704 },
  },
  {
    name: 'Kenya',
    iso2: 'KE',
    iso3: 'KEN',
    flag: 'https://flagcdn.com/ke.svg',
    currency: 'KES',
    capital: 'Nairobi',
    region: 'Africa',
    coordinates: { lat: -1.2864, lng: 36.8172 },
  },
  {
    name: 'Kiribati',
    iso2: 'KI',
    iso3: 'KIR',
    flag: 'https://flagcdn.com/ki.svg',
    currency: 'AUD',
    capital: 'Tarawa',
    region: 'Oceania',
    coordinates: { lat: 1.4518, lng: 173.0308 },
  },
  {
    name: 'Kuwait',
    iso2: 'KW',
    iso3: 'KWT',
    flag: 'https://flagcdn.com/kw.svg',
    currency: 'KWD',
    capital: 'Kuwait City',
    region: 'Asia',
    coordinates: { lat: 29.3759, lng: 47.9774 },
  },
  {
    name: 'Kyrgyzstan',
    iso2: 'KG',
    iso3: 'KGZ',
    flag: 'https://flagcdn.com/kg.svg',
    currency: 'KGS',
    capital: 'Bishkek',
    region: 'Asia',
    coordinates: { lat: 42.8746, lng: 74.5698 },
  },
  {
    name: 'Laos',
    iso2: 'LA',
    iso3: 'LAO',
    flag: 'https://flagcdn.com/la.svg',
    currency: 'LAK',
    capital: 'Vientiane',
    region: 'Asia',
    coordinates: { lat: 17.9757, lng: 102.6331 },
  },
  {
    name: 'Latvia',
    iso2: 'LV',
    iso3: 'LVA',
    flag: 'https://flagcdn.com/lv.svg',
    currency: 'EUR',
    capital: 'Riga',
    coordinates: { lat: 56.9496, lng: 24.1052 },
    region: 'Europe',
  },
  {
    name: 'Lebanon',
    iso2: 'LB',
    iso3: 'LBN',
    flag: 'https://flagcdn.com/lb.svg',
    currency: 'LBP',
    capital: 'Beirut',
    coordinates: { lat: 33.8938, lng: 35.5018 },
    region: 'Asia',
  },
  {
    name: 'Lesotho',
    iso2: 'LS',
    iso3: 'LSO',
    flag: 'https://flagcdn.com/ls.svg',
    currency: 'LSL',
    capital: 'Maseru',
    coordinates: { lat: -29.3151, lng: 27.4869 },
    region: 'Africa',
  },
  {
    name: 'Liberia',
    iso2: 'LR',
    iso3: 'LBR',
    flag: 'https://flagcdn.com/lr.svg',
    currency: 'LRD',
    capital: 'Monrovia',
    coordinates: { lat: 6.3005, lng: -10.7972 },
    region: 'Africa',
  },
  {
    name: 'Libya',
    iso2: 'LY',
    iso3: 'LBY',
    flag: 'https://flagcdn.com/ly.svg',
    currency: 'LYD',
    capital: 'Tripoli',
    coordinates: { lat: 32.8872, lng: 13.1913 },
    region: 'Africa',
  },
  {
    name: 'Liechtenstein',
    iso2: 'LI',
    iso3: 'LIE',
    flag: 'https://flagcdn.com/li.svg',
    currency: 'CHF',
    capital: 'Vaduz',
    coordinates: { lat: 47.141, lng: 9.5215 },
    region: 'Europe',
  },
  {
    name: 'Lithuania',
    iso2: 'LT',
    iso3: 'LTU',
    flag: 'https://flagcdn.com/lt.svg',
    currency: 'EUR',
    capital: 'Vilnius',
    coordinates: { lat: 54.6872, lng: 25.2797 },
    region: 'Europe',
  },
  {
    name: 'Luxembourg',
    iso2: 'LU',
    iso3: 'LUX',
    flag: 'https://flagcdn.com/lu.svg',
    currency: 'EUR',
    capital: 'Luxembourg City',
    coordinates: { lat: 49.6117, lng: 6.13 },
    region: 'Europe',
  },
  {
    name: 'Madagascar',
    iso2: 'MG',
    iso3: 'MDG',
    flag: 'https://flagcdn.com/mg.svg',
    currency: 'MGA',
    capital: 'Antananarivo',
    coordinates: { lat: -18.8792, lng: 47.5079 },
    region: 'Africa',
  },
  {
    name: 'Malawi',
    iso2: 'MW',
    iso3: 'MWI',
    flag: 'https://flagcdn.com/mw.svg',
    currency: 'MWK',
    capital: 'Lilongwe',
    coordinates: { lat: -13.9626, lng: 33.7741 },
    region: 'Africa',
  },
  {
    name: 'Malaysia',
    iso2: 'MY',
    iso3: 'MYS',
    flag: 'https://flagcdn.com/my.svg',
    currency: 'MYR',
    capital: 'Kuala Lumpur',
    coordinates: { lat: 3.139, lng: 101.6869 },
    region: 'Asia',
  },
  {
    name: 'Maldives',
    iso2: 'MV',
    iso3: 'MDV',
    flag: 'https://flagcdn.com/mv.svg',
    currency: 'MVR',
    capital: 'Malé',
    coordinates: { lat: 4.1755, lng: 73.5093 },
    region: 'Asia',
  },
  {
    name: 'Mali',
    iso2: 'ML',
    iso3: 'MLI',
    flag: 'https://flagcdn.com/ml.svg',
    currency: 'XOF',
    capital: 'Bamako',
    coordinates: { lat: 12.6392, lng: -8.0029 },
    region: 'Africa',
  },
  {
    name: 'Malta',
    iso2: 'MT',
    iso3: 'MLT',
    flag: 'https://flagcdn.com/mt.svg',
    currency: 'EUR',
    capital: 'Valletta',
    coordinates: { lat: 35.8997, lng: 14.5147 },
    region: 'Europe',
  },
  {
    name: 'Marshall Islands',
    iso2: 'MH',
    iso3: 'MHL',
    flag: 'https://flagcdn.com/mh.svg',
    currency: 'USD',
    capital: 'Majuro',
    coordinates: { lat: 7.1164, lng: 171.185 },
    region: 'Oceania',
  },
  {
    name: 'Mauritania',
    iso2: 'MR',
    iso3: 'MRT',
    flag: 'https://flagcdn.com/mr.svg',
    currency: 'MRU',
    capital: 'Nouakchott',
    coordinates: { lat: 18.0735, lng: -15.9582 },
    region: 'Africa',
  },
  {
    name: 'Mauritius',
    iso2: 'MU',
    iso3: 'MUS',
    flag: 'https://flagcdn.com/mu.svg',
    currency: 'MUR',
    capital: 'Port Louis',
    coordinates: { lat: -20.1609, lng: 57.5012 },
    region: 'Africa',
  },
  {
    name: 'Mexico',
    iso2: 'MX',
    iso3: 'MEX',
    flag: 'https://flagcdn.com/mx.svg',
    currency: 'MXN',
    capital: 'Mexico City',
    coordinates: { lat: 19.4326, lng: -99.1332 },
    region: 'North America',
  },
  {
    name: 'Micronesia',
    iso2: 'FM',
    iso3: 'FSM',
    flag: 'https://flagcdn.com/fm.svg',
    currency: 'USD',
    capital: 'Palikir',
    coordinates: { lat: 6.9147, lng: 158.161 },
    region: 'Oceania',
  },
  {
    name: 'Moldova',
    iso2: 'MD',
    iso3: 'MDA',
    flag: 'https://flagcdn.com/md.svg',
    currency: 'MDL',
    capital: 'Chișinău',
    coordinates: { lat: 47.0105, lng: 28.8638 },
    region: 'Europe',
  },
  {
    name: 'Monaco',
    iso2: 'MC',
    iso3: 'MCO',
    flag: 'https://flagcdn.com/mc.svg',
    currency: 'EUR',
    capital: 'Monaco',
    coordinates: { lat: 43.7384, lng: 7.4246 },
    region: 'Europe',
  },
  {
    name: 'Mongolia',
    iso2: 'MN',
    iso3: 'MNG',
    flag: 'https://flagcdn.com/mn.svg',
    currency: 'MNT',
    capital: 'Ulaanbaatar',
    coordinates: { lat: 47.8864, lng: 106.9057 },
    region: 'Asia',
  },
  {
    name: 'Montenegro',
    iso2: 'ME',
    iso3: 'MNE',
    flag: 'https://flagcdn.com/me.svg',
    currency: 'EUR',
    capital: 'Podgorica',
    coordinates: { lat: 42.4304, lng: 19.2594 },
    region: 'Europe',
  },
  {
    name: 'Morocco',
    iso2: 'MA',
    iso3: 'MAR',
    flag: 'https://flagcdn.com/ma.svg',
    currency: 'MAD',
    capital: 'Rabat',
    coordinates: { lat: 34.0209, lng: -6.8416 },
    region: 'Africa',
  },
  {
    name: 'Mozambique',
    iso2: 'MZ',
    iso3: 'MOZ',
    flag: 'https://flagcdn.com/mz.svg',
    currency: 'MZN',
    capital: 'Maputo',
    coordinates: { lat: -25.9692, lng: 32.5732 },
    region: 'Africa',
  },
  {
    name: 'Myanmar',
    iso2: 'MM',
    iso3: 'MMR',
    flag: 'https://flagcdn.com/mm.svg',
    currency: 'MMK',
    capital: 'Naypyidaw',
    coordinates: { lat: 19.7633, lng: 96.0785 },
    region: 'Asia',
  },
  {
    name: 'Namibia',
    iso2: 'NA',
    iso3: 'NAM',
    flag: 'https://flagcdn.com/na.svg',
    currency: 'NAD',
    capital: 'Windhoek',
    coordinates: { lat: -22.5609, lng: 17.0658 },
    region: 'Africa',
  },
  {
    name: 'Nauru',
    iso2: 'NR',
    iso3: 'NRU',
    flag: 'https://flagcdn.com/nr.svg',
    currency: 'AUD',
    capital: 'Yaren District',
    coordinates: { lat: -0.5477, lng: 166.9209 },
    region: 'Oceania',
  },
  {
    name: 'Nepal',
    iso2: 'NP',
    iso3: 'NPL',
    flag: 'https://flagcdn.com/np.svg',
    currency: 'NPR',
    capital: 'Kathmandu',
    coordinates: { lat: 27.7172, lng: 85.324 },
    region: 'Asia',
  },
  {
    name: 'Netherlands',
    iso2: 'NL',
    iso3: 'NLD',
    flag: 'https://flagcdn.com/nl.svg',
    currency: 'EUR',
    capital: 'Amsterdam',
    coordinates: { lat: 52.3676, lng: 4.9041 },
    region: 'Europe',
  },
  {
    name: 'New Zealand',
    iso2: 'NZ',
    iso3: 'NZL',
    flag: 'https://flagcdn.com/nz.svg',
    currency: 'NZD',
    capital: 'Wellington',
    coordinates: { lat: -41.2865, lng: 174.7762 },
    region: 'Oceania',
  },
  {
    name: 'Nicaragua',
    iso2: 'NI',
    iso3: 'NIC',
    flag: 'https://flagcdn.com/ni.svg',
    currency: 'NIO',
    capital: 'Managua',
    coordinates: { lat: 12.1364, lng: -86.2514 },
    region: 'North America',
  },
  {
    name: 'Niger',
    iso2: 'NE',
    iso3: 'NER',
    flag: 'https://flagcdn.com/ne.svg',
    currency: 'XOF',
    capital: 'Niamey',
    coordinates: { lat: 13.5116, lng: 2.1254 },
    region: 'Africa',
  },
  {
    name: 'Nigeria',
    iso2: 'NG',
    iso3: 'NGA',
    flag: 'https://flagcdn.com/ng.svg',
    currency: 'NGN',
    capital: 'Abuja',
    coordinates: { lat: 9.0765, lng: 7.3986 },
    region: 'Africa',
  },
  {
    name: 'North Korea',
    iso2: 'KP',
    iso3: 'PRK',
    flag: 'https://flagcdn.com/kp.svg',
    currency: 'KPW',
    capital: 'Pyongyang',
    coordinates: { lat: 39.0392, lng: 125.7625 },
    region: 'Asia',
  },
  {
    name: 'North Macedonia',
    iso2: 'MK',
    iso3: 'MKD',
    flag: 'https://flagcdn.com/mk.svg',
    currency: 'MKD',
    capital: 'Skopje',
    coordinates: { lat: 41.9973, lng: 21.428 },
    region: 'Europe',
  },
  {
    name: 'Norway',
    iso2: 'NO',
    iso3: 'NOR',
    flag: 'https://flagcdn.com/no.svg',
    currency: 'NOK',
    capital: 'Oslo',
    coordinates: { lat: 59.9139, lng: 10.7522 },
    region: 'Europe',
  },
  {
    name: 'Oman',
    iso2: 'OM',
    iso3: 'OMN',
    flag: 'https://flagcdn.com/om.svg',
    currency: 'OMR',
    capital: 'Muscat',
    coordinates: { lat: 23.588, lng: 58.3829 },
    region: 'Asia',
  },
  {
    name: 'Pakistan',
    iso2: 'PK',
    iso3: 'PAK',
    flag: 'https://flagcdn.com/pk.svg',
    currency: 'PKR',
    capital: 'Islamabad',
    coordinates: { lat: 33.6844, lng: 73.0479 },
    region: 'Asia',
  },
  {
    name: 'Palau',
    iso2: 'PW',
    iso3: 'PLW',
    flag: 'https://flagcdn.com/pw.svg',
    currency: 'USD',
    capital: 'Ngerulmud',
    coordinates: { lat: 7.5004, lng: 134.6243 },
    region: 'Oceania',
  },
  {
    name: 'Panama',
    iso2: 'PA',
    iso3: 'PAN',
    flag: 'https://flagcdn.com/pa.svg',
    currency: 'PAB',
    capital: 'Panama City',
    coordinates: { lat: 8.9824, lng: -79.5199 },
    region: 'North America',
  },
  {
    name: 'Papua New Guinea',
    iso2: 'PG',
    iso3: 'PNG',
    flag: 'https://flagcdn.com/pg.svg',
    currency: 'PGK',
    capital: 'Port Moresby',
    coordinates: { lat: -9.4438, lng: 147.1803 },
    region: 'Oceania',
  },
  {
    name: 'Paraguay',
    iso2: 'PY',
    iso3: 'PRY',
    flag: 'https://flagcdn.com/py.svg',
    currency: 'PYG',
    capital: 'Asunción',
    coordinates: { lat: -25.2637, lng: -57.5759 },
    region: 'South America',
  },
  {
    name: 'Peru',
    iso2: 'PE',
    iso3: 'PER',
    flag: 'https://flagcdn.com/pe.svg',
    currency: 'PEN',
    capital: 'Lima',
    coordinates: { lat: -12.0464, lng: -77.0428 },
    region: 'South America',
  },
  {
    name: 'Philippines',
    iso2: 'PH',
    iso3: 'PHL',
    flag: 'https://flagcdn.com/ph.svg',
    currency: 'PHP',
    capital: 'Manila',
    coordinates: { lat: 14.5995, lng: 120.9842 },
    region: 'Asia',
  },
  {
    name: 'Poland',
    iso2: 'PL',
    iso3: 'POL',
    flag: 'https://flagcdn.com/pl.svg',
    currency: 'PLN',
    capital: 'Warsaw',
    coordinates: { lat: 52.2298, lng: 21.0118 },
    region: 'Europe',
  },
  {
    name: 'Portugal',
    iso2: 'PT',
    iso3: 'PRT',
    flag: 'https://flagcdn.com/pt.svg',
    currency: 'EUR',
    capital: 'Lisbon',
    coordinates: { lat: 38.7223, lng: -9.1393 },
    region: 'Europe',
  },
  {
    name: 'Qatar',
    iso2: 'QA',
    iso3: 'QAT',
    flag: 'https://flagcdn.com/qa.svg',
    currency: 'QAR',
    capital: 'Doha',
    coordinates: { lat: 25.2854, lng: 51.531 },
    region: 'Asia',
  },
  {
    name: 'Romania',
    iso2: 'RO',
    iso3: 'ROU',
    flag: 'https://flagcdn.com/ro.svg',
    currency: 'RON',
    capital: 'Bucharest',
    coordinates: { lat: 44.4268, lng: 26.1025 },
    region: 'Europe',
  },
  {
    name: 'Russia',
    iso2: 'RU',
    iso3: 'RUS',
    flag: 'https://flagcdn.com/ru.svg',
    currency: 'RUB',
    capital: 'Moscow',
    coordinates: { lat: 55.7558, lng: 37.6173 },
    region: 'Europe',
  },
  {
    name: 'Rwanda',
    iso2: 'RW',
    iso3: 'RWA',
    flag: 'https://flagcdn.com/rw.svg',
    currency: 'RWF',
    capital: 'Kigali',
    coordinates: { lat: -1.9441, lng: 30.0619 },
    region: 'Africa',
  },
  {
    name: 'Saint Kitts and Nevis',
    iso2: 'KN',
    iso3: 'KNA',
    flag: 'https://flagcdn.com/kn.svg',
    currency: 'XCD',
    capital: 'Basseterre',
    coordinates: { lat: 17.3026, lng: -62.7177 },
    region: 'North America',
  },
  {
    name: 'Saint Lucia',
    iso2: 'LC',
    iso3: 'LCA',
    flag: 'https://flagcdn.com/lc.svg',
    currency: 'XCD',
    capital: 'Castries',
    coordinates: { lat: 13.9094, lng: -60.9789 },
    region: 'North America',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    iso3: 'VCT',
    flag: 'https://flagcdn.com/vc.svg',
    currency: 'XCD',
    capital: 'Kingstown',
    coordinates: { lat: 13.16, lng: -61.224 },
    region: 'North America',
  },
  {
    name: 'Samoa',
    iso2: 'WS',
    iso3: 'WSM',
    flag: 'https://flagcdn.com/ws.svg',
    currency: 'WST',
    capital: 'Apia',
    coordinates: { lat: -13.8333, lng: -171.7667 },
    region: 'Oceania',
  },
  {
    name: 'San Marino',
    iso2: 'SM',
    iso3: 'SMR',
    flag: 'https://flagcdn.com/sm.svg',
    currency: 'EUR',
    capital: 'San Marino',
    coordinates: { lat: 43.9333, lng: 12.45 },
    region: 'Europe',
  },
  {
    name: 'Sao Tome and Principe',
    iso2: 'ST',
    iso3: 'STP',
    flag: 'https://flagcdn.com/st.svg',
    currency: 'STN',
    capital: 'São Tomé',
    coordinates: { lat: 0.3365, lng: 6.7273 },
    region: 'Africa',
  },
  {
    name: 'Saudi Arabia',
    iso2: 'SA',
    iso3: 'SAU',
    flag: 'https://flagcdn.com/sa.svg',
    currency: 'SAR',
    capital: 'Riyadh',
    coordinates: { lat: 24.7136, lng: 46.6753 },
    region: 'Asia',
  },
  {
    name: 'Senegal',
    iso2: 'SN',
    iso3: 'SEN',
    flag: 'https://flagcdn.com/sn.svg',
    currency: 'XOF',
    capital: 'Dakar',
    coordinates: { lat: 14.7167, lng: -17.4677 },
    region: 'Africa',
  },
  {
    name: 'Serbia',
    iso2: 'RS',
    iso3: 'SRB',
    flag: 'https://flagcdn.com/rs.svg',
    currency: 'RSD',
    capital: 'Belgrade',
    coordinates: { lat: 44.7866, lng: 20.4489 },
    region: 'Europe',
  },
  {
    name: 'Seychelles',
    iso2: 'SC',
    iso3: 'SYC',
    flag: 'https://flagcdn.com/sc.svg',
    currency: 'SCR',
    capital: 'Victoria',
    coordinates: { lat: -4.6191, lng: 55.4513 },
    region: 'Africa',
  },
  {
    name: 'Sierra Leone',
    iso2: 'SL',
    iso3: 'SLE',
    flag: 'https://flagcdn.com/sl.svg',
    currency: 'SLE',
    capital: 'Freetown',
    coordinates: { lat: 8.4844, lng: -13.2344 },
    region: 'Africa',
  },
  {
    name: 'Singapore',
    iso2: 'SG',
    iso3: 'SGP',
    flag: 'https://flagcdn.com/sg.svg',
    currency: 'SGD',
    capital: 'Singapore',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    region: 'Asia',
  },
  {
    name: 'Slovakia',
    iso2: 'SK',
    iso3: 'SVK',
    flag: 'https://flagcdn.com/sk.svg',
    currency: 'EUR',
    capital: 'Bratislava',
    coordinates: { lat: 48.1486, lng: 17.1077 },
    region: 'Europe',
  },
  {
    name: 'Slovenia',
    iso2: 'SI',
    iso3: 'SVN',
    flag: 'https://flagcdn.com/si.svg',
    currency: 'EUR',
    capital: 'Ljubljana',
    coordinates: { lat: 46.0569, lng: 14.5058 },
    region: 'Europe',
  },
  {
    name: 'Solomon Islands',
    iso2: 'SB',
    iso3: 'SLB',
    flag: 'https://flagcdn.com/sb.svg',
    currency: 'SBD',
    capital: 'Honiara',
    coordinates: { lat: -9.4456, lng: 159.9729 },
    region: 'Oceania',
  },
  {
    name: 'Somalia',
    iso2: 'SO',
    iso3: 'SOM',
    flag: 'https://flagcdn.com/so.svg',
    currency: 'SOS',
    capital: 'Mogadishu',
    coordinates: { lat: 2.0469, lng: 45.3182 },
    region: 'Africa',
  },
  {
    name: 'South Africa',
    iso2: 'ZA',
    iso3: 'ZAF',
    flag: 'https://flagcdn.com/za.svg',
    currency: 'ZAR',
    capital: 'Pretoria',
    coordinates: { lat: -25.7479, lng: 28.2293 },
    region: 'Africa',
  },
  {
    name: 'South Korea',
    iso2: 'KR',
    iso3: 'KOR',
    flag: 'https://flagcdn.com/kr.svg',
    currency: 'KRW',
    capital: 'Seoul',
    coordinates: { lat: 37.5665, lng: 126.978 },
    region: 'Asia',
  },
  {
    name: 'South Sudan',
    iso2: 'SS',
    iso3: 'SSD',
    flag: 'https://flagcdn.com/ss.svg',
    currency: 'SSP',
    capital: 'Juba',
    coordinates: { lat: 4.8594, lng: 31.5713 },
    region: 'Africa',
  },
  {
    name: 'Spain',
    iso2: 'ES',
    iso3: 'ESP',
    flag: 'https://flagcdn.com/es.svg',
    currency: 'EUR',
    capital: 'Madrid',
    coordinates: { lat: 40.4168, lng: -3.7038 },
    region: 'Europe',
  },
  {
    name: 'Sri Lanka',
    iso2: 'LK',
    iso3: 'LKA',
    flag: 'https://flagcdn.com/lk.svg',
    currency: 'LKR',
    capital: 'Sri Jayawardenepura Kotte',
    coordinates: { lat: 6.8941, lng: 79.902 },
    region: 'Asia',
  },
  {
    name: 'Sudan',
    iso2: 'SD',
    iso3: 'SDN',
    flag: 'https://flagcdn.com/sd.svg',
    currency: 'SDG',
    capital: 'Khartoum',
    coordinates: { lat: 15.5007, lng: 32.5599 },
    region: 'Africa',
  },
  {
    name: 'Suriname',
    iso2: 'SR',
    iso3: 'SUR',
    flag: 'https://flagcdn.com/sr.svg',
    currency: 'SRD',
    capital: 'Paramaribo',
    coordinates: { lat: 5.852, lng: -55.2038 },
    region: 'South America',
  },
  {
    name: 'Sweden',
    iso2: 'SE',
    iso3: 'SWE',
    flag: 'https://flagcdn.com/se.svg',
    currency: 'SEK',
    capital: 'Stockholm',
    coordinates: { lat: 59.3293, lng: 18.0686 },
    region: 'Europe',
  },
  {
    name: 'Switzerland',
    iso2: 'CH',
    iso3: 'CHE',
    flag: 'https://flagcdn.com/ch.svg',
    currency: 'CHF',
    capital: 'Bern',
    coordinates: { lat: 46.948, lng: 7.4474 },
    region: 'Europe',
  },
  {
    name: 'Syria',
    iso2: 'SY',
    iso3: 'SYR',
    flag: 'https://flagcdn.com/sy.svg',
    currency: 'SYP',
    capital: 'Damascus',
    coordinates: { lat: 33.5138, lng: 36.2765 },
    region: 'Asia',
  },
  {
    name: 'Tajikistan',
    iso2: 'TJ',
    iso3: 'TJK',
    flag: 'https://flagcdn.com/tj.svg',
    currency: 'TJS',
    capital: 'Dushanbe',
    coordinates: { lat: 38.5598, lng: 68.787 },
    region: 'Asia',
  },
  {
    name: 'Tanzania',
    iso2: 'TZ',
    iso3: 'TZA',
    flag: 'https://flagcdn.com/tz.svg',
    currency: 'TZS',
    capital: 'Dodoma',
    coordinates: { lat: -6.163, lng: 35.7516 },
    region: 'Africa',
  },
  {
    name: 'Thailand',
    iso2: 'TH',
    iso3: 'THA',
    flag: 'https://flagcdn.com/th.svg',
    currency: 'THB',
    capital: 'Bangkok',
    coordinates: { lat: 13.7563, lng: 100.5018 },
    region: 'Asia',
  },
  {
    name: 'Timor-Leste',
    iso2: 'TL',
    iso3: 'TLS',
    flag: 'https://flagcdn.com/tl.svg',
    currency: 'USD',
    capital: 'Dili',
    coordinates: { lat: -8.5569, lng: 125.5603 },
    region: 'Asia',
  },
  {
    name: 'Togo',
    iso2: 'TG',
    iso3: 'TGO',
    flag: 'https://flagcdn.com/tg.svg',
    currency: 'XOF',
    capital: 'Lomé',
    coordinates: { lat: 6.1375, lng: 1.2123 },
    region: 'Africa',
  },
  {
    name: 'Tonga',
    iso2: 'TO',
    iso3: 'TON',
    flag: 'https://flagcdn.com/to.svg',
    currency: 'TOP',
    capital: 'Nukuʻalofa',
    coordinates: { lat: -21.1394, lng: -175.2018 },
    region: 'Oceania',
  },
  {
    name: 'Trinidad and Tobago',
    iso2: 'TT',
    iso3: 'TTO',
    flag: 'https://flagcdn.com/tt.svg',
    currency: 'TTD',
    capital: 'Port of Spain',
    coordinates: { lat: 10.6667, lng: -61.5167 },
    region: 'North America',
  },
  {
    name: 'Tunisia',
    iso2: 'TN',
    iso3: 'TUN',
    flag: 'https://flagcdn.com/tn.svg',
    currency: 'TND',
    capital: 'Tunis',
    coordinates: { lat: 36.8065, lng: 10.1815 },
    region: 'Africa',
  },
  {
    name: 'Turkey',
    iso2: 'TR',
    iso3: 'TUR',
    flag: 'https://flagcdn.com/tr.svg',
    currency: 'TRY',
    capital: 'Ankara',
    coordinates: { lat: 39.9334, lng: 32.8597 },
    region: 'Asia',
  },
  {
    name: 'Turkmenistan',
    iso2: 'TM',
    iso3: 'TKM',
    flag: 'https://flagcdn.com/tm.svg',
    currency: 'TMT',
    capital: 'Ashgabat',
    coordinates: { lat: 37.9601, lng: 58.3261 },
    region: 'Asia',
  },
  {
    name: 'Tuvalu',
    iso2: 'TV',
    iso3: 'TUV',
    flag: 'https://flagcdn.com/tv.svg',
    currency: 'AUD',
    capital: 'Funafuti',
    coordinates: { lat: -8.5167, lng: 179.2167 },
    region: 'Oceania',
  },
  {
    name: 'Uganda',
    iso2: 'UG',
    iso3: 'UGA',
    flag: 'https://flagcdn.com/ug.svg',
    currency: 'UGX',
    capital: 'Kampala',
    coordinates: { lat: 0.3476, lng: 32.5825 },
    region: 'Africa',
  },
  {
    name: 'Ukraine',
    iso2: 'UA',
    iso3: 'UKR',
    flag: 'https://flagcdn.com/ua.svg',
    currency: 'UAH',
    capital: 'Kyiv',
    coordinates: { lat: 50.4501, lng: 30.5234 },
    region: 'Europe',
  },
  {
    name: 'United Arab Emirates',
    iso2: 'AE',
    iso3: 'ARE',
    flag: 'https://flagcdn.com/ae.svg',
    currency: 'AED',
    capital: 'Abu Dhabi',
    coordinates: { lat: 24.4539, lng: 54.3773 },
    region: 'Asia',
  },
  {
    name: 'United Kingdom',
    iso2: 'GB',
    iso3: 'GBR',
    flag: 'https://flagcdn.com/gb.svg',
    currency: 'GBP',
    capital: 'London',
    coordinates: { lat: 51.5072, lng: -0.1276 },
    region: 'Europe',
  },
  {
    name: 'United States',
    iso2: 'US',
    iso3: 'USA',
    flag: 'https://flagcdn.com/us.svg',
    currency: 'USD',
    capital: 'Washington, D.C.',
    coordinates: { lat: 38.9072, lng: -77.0369 },
    region: 'North America',
  },
  {
    name: 'Uruguay',
    iso2: 'UY',
    iso3: 'URY',
    flag: 'https://flagcdn.com/uy.svg',
    currency: 'UYU',
    capital: 'Montevideo',
    coordinates: { lat: -34.9011, lng: -56.1645 },
    region: 'South America',
  },
  {
    name: 'Uzbekistan',
    iso2: 'UZ',
    iso3: 'UZB',
    flag: 'https://flagcdn.com/uz.svg',
    currency: 'UZS',
    capital: 'Tashkent',
    coordinates: { lat: 41.2995, lng: 69.24 },
    region: 'Asia',
  },
  {
    name: 'Vanuatu',
    iso2: 'VU',
    iso3: 'VUT',
    flag: 'https://flagcdn.com/vu.svg',
    currency: 'VUV',
    capital: 'Port Vila',
    coordinates: { lat: -17.7333, lng: 168.3167 },
    region: 'Oceania',
  },
  {
    name: 'Vatican City',
    iso2: 'VA',
    iso3: 'VAT',
    flag: 'https://flagcdn.com/va.svg',
    currency: 'EUR',
    capital: 'Vatican City',
    coordinates: { lat: 41.9029, lng: 12.4534 },
    region: 'Europe',
  },
  {
    name: 'Venezuela',
    iso2: 'VE',
    iso3: 'VEN',
    flag: 'https://flagcdn.com/ve.svg',
    currency: 'VES',
    capital: 'Caracas',
    coordinates: { lat: 10.4806, lng: -66.9036 },
    region: 'South America',
  },
  {
    name: 'Vietnam',
    iso2: 'VN',
    iso3: 'VNM',
    flag: 'https://flagcdn.com/vn.svg',
    currency: 'VND',
    capital: 'Hanoi',
    coordinates: { lat: 21.0278, lng: 105.8342 },
    region: 'Asia',
  },
  {
    name: 'Yemen',
    iso2: 'YE',
    iso3: 'YEM',
    flag: 'https://flagcdn.com/ye.svg',
    currency: 'YER',
    capital: "Sana'a",
    coordinates: { lat: 15.3694, lng: 44.191 },
    region: 'Asia',
  },
  {
    name: 'Zambia',
    iso2: 'ZM',
    iso3: 'ZMB',
    flag: 'https://flagcdn.com/zm.svg',
    currency: 'ZMW',
    capital: 'Lusaka',
    coordinates: { lat: -15.3875, lng: 28.3228 },
    region: 'Africa',
  },
  {
    name: 'Zimbabwe',
    iso2: 'ZW',
    iso3: 'ZWE',
    flag: 'https://flagcdn.com/zw.svg',
    currency: 'ZWL',
    capital: 'Harare',
    coordinates: { lat: -17.8292, lng: 31.0522 },
    region: 'Africa',
  },
];
